package Mastermind;

import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 * @author Ryan O'Shea
 *
 * Copyright © 2009-2011 Ryan O'Shea
 *
 * Copying Permissions: 
 * 	This file is part of Mastermind.
 *
 * 	Mastermind is free software: you can redistribute it and/or modify
 * 	it under the terms of the GNU General Public License as published by
 * 	the Free Software Foundation, either version 3 of the License, or
 * 	(at your option) any later version.
 * 
 * 	Mastermind is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 *  along with Mastermind (see the "COPYING" file).  If not, see <http://www.gnu.org/licenses/>.
 */

public class GameConfig extends javax.swing.JFrame {

    /** Creates new form GameConfig */
    public GameConfig() {
	initComponents();
	SpinnerModel model1 = new SpinnerNumberModel(4, 1, 10, 1);
        this.jSpinnerNDigits.setModel(model1);
	SpinnerModel model2 = new SpinnerNumberModel(4, 1, 9, 1);
        this.jSpinnerRange.setModel(model2);
	SpinnerModel model3 = new SpinnerNumberModel(10, 1, 99, 1);
        this.jSpinnerNGuesses.setModel(model3);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerRange = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerNDigits = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerNGuesses = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonSubmitConfig = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinnerRange.setFont(new java.awt.Font("Segoe UI", 1, 24));
        getContentPane().add(jSpinnerRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 258, 54, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel5.setText("Guesses Allowed:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 316, -1, -1));

        jSpinnerNDigits.setFont(new java.awt.Font("Segoe UI", 1, 24));
        getContentPane().add(jSpinnerNDigits, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 209, 54, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel4.setText("Range of each Digit: 1 to");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 267, -1, -1));

        jSpinnerNGuesses.setFont(new java.awt.Font("Segoe UI", 1, 24));
        getContentPane().add(jSpinnerNGuesses, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 307, 54, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel3.setText("Number of Digits to Guess:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 218, -1, -1));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Mastermind");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 410, 42));

        jButtonSubmitConfig.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButtonSubmitConfig.setText("Start Game");
        jButtonSubmitConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitConfigActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubmitConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 216, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html><p><strong>The object of the game is to guess a number, chosen at random.</strong> </p><p>Each guess will be compared to the target number. </p><p>A RED peg means that one of the numbers in your guess exists and is in the correct place in the target number. </p><p>A WHITE peg means that one of the numbers in your guess exists in the target number, but not in the same location as it is in your guess.</p></html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 380, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13));
        jLabel1.setText("Game Rules");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 95, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("by Ryan O'Shea");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int nGuesses = 0, range = 0, nDigits = 0;
    
    private void jButtonSubmitConfigActionPerformed(java.awt.event.ActionEvent evt) {

	nDigits = Integer.parseInt(jSpinnerNDigits.getValue().toString());
	range = Integer.parseInt(jSpinnerRange.getValue().toString());
	nGuesses = Integer.parseInt(jSpinnerNGuesses.getValue().toString());
	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(GameConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(GameConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(GameConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(GameConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		new GameConfig().setVisible(true);
	    }
	});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmitConfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JSpinner jSpinnerNDigits;
    private javax.swing.JSpinner jSpinnerNGuesses;
    private javax.swing.JSpinner jSpinnerRange;
    // End of variables declaration//GEN-END:variables

    int getNDigits() {
	return nDigits;
    }

    int getRange() {
	return range;
    }

    int getNGuesses() {
	return nGuesses;
    }
}
